/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "RomanCalculator-test.check" instead.
 */

#include <check.h>

#line 1 "RomanCalculator-test.check"
/*
 * RomanCalculator-test.c
 *
 *  Created on: Mar 28, 2017
 *      Author: Alex Williams
 */
 
 #include <string.h>
 #include <stdlib.h>
 #include <stdio.h>
 #include "RomanConverter.h"
 
START_TEST(romanToIntTestOne)
{
#line 14
 	fail_unless(romanToInt("i") == 1, "%d is not 1", romanToInt("i"));
 	fail_unless(romanToInt("I") == 1, "%d is not 1", romanToInt("I"));
 	fail_unless(romanToInt("V") == 5, "%d is not 5", romanToInt("V"));
 	fail_unless(romanToInt("X") == 10, "%d is not 10", romanToInt("X"));
 	fail_unless(romanToInt("L") == 50, "%d is not 50", romanToInt("L"));
 	fail_unless(romanToInt("C") == 100, "%d is not 100", romanToInt("C"));
 	fail_unless(romanToInt("D") == 500, "%d is not 500", romanToInt("D"));
 	fail_unless(romanToInt("M") == 1000, "%d is not 1000", romanToInt("M"));
 	fail_unless(romanToInt("MDCLXVI") == 1666, "%d is not 1666", romanToInt("M"));
 	fail_unless(romanToInt("IV") == 4, "%d is not 4", romanToInt("IV"));
 	fail_unless(romanToInt("IX") == 9, "%d is not 9", romanToInt("IX"));
 	fail_unless(romanToInt("XL") == 40, "%d is not 40", romanToInt("XL"));
 	fail_unless(romanToInt("XC") == 90, "%d is not 90", romanToInt("XC"));
 	fail_unless(romanToInt("CD") == 400, "%d is not 400", romanToInt("CD"));
 	fail_unless(romanToInt("CM") == 900, "%d is not 900", romanToInt("CM"));
 	fail_unless(romanToInt("IVIX") == -1, "%d is not -1", romanToInt("IVIX"));
 	fail_unless(romanToInt("IXIV") == -1, "%d is not -1", romanToInt("IXIV"));
 	fail_unless(romanToInt("IVI") == -1, "%d is not -1", romanToInt("IVI"));
 	fail_unless(romanToInt("CMXCIX") == 999, "%d is not 999", romanToInt("CMXCIX"));
 	fail_unless(romanToInt("CMXCIIX") == -1, "%d is not -1", romanToInt("CMXCIIX"));
 	fail_unless(romanToInt("MCMXCIX") == 1999, "%d is not 1999", romanToInt("MCMXCIX"));
 	fail_unless(romanToInt("MCMXCXLIX") == -1, "%d is not -1", romanToInt("MCMXCXLIX"));
 	fail_unless(romanToInt("IIII") == -1, "%d is not -1", romanToInt("IIII"));
 	fail_unless(romanToInt("VIV") == -1, "%d is not -1", romanToInt("VIV"));
 	fail_unless(romanToInt("VV") == -1, "%d is not -1", romanToInt("VV"));
 	fail_unless(romanToInt("DD") == -1, "%d is not -1", romanToInt("DD"));
 	fail_unless(romanToInt("LL") == -1, "%d is not -1", romanToInt("LL"));
 	fail_unless(romanToInt("MMMCMXCIX") == 3999, "%d is not 3999", romanToInt("MMMCMXCIX"));
 	
}
END_TEST

START_TEST(intToRomanTest)
{
#line 44
 	char num[10] = "";
	intToRoman(3999, num);
 	fail_unless(strcmp(num,"MMMCMXCIX") == 0, "%s does not equal MMMCMXCIX", num);
 	num[0] = '\0';
 	intToRoman(1, num);
 	fail_unless(strcmp(num,"I") == 0, "%s does not equal I", num);
 	num[0] = '\0';
 	intToRoman(3444, num);
 	fail_unless(strcmp(num,"MMMCDXLIV") == 0, "%s does not equal MMMCDKLIV", num);
 	num[0] = '\0';
 	intToRoman(0, num);
 	fail_unless(strcmp(num,"Nulla") == 0, "%s does not equal Nulla", num);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, romanToIntTestOne);
    tcase_add_test(tc1_1, intToRomanTest);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
